FROM ubuntu:noble

# Installing base, Latex related packages

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive && \
    apt-get install -y texlive-lang-all asymptote biber chktex \
    cm-super context dvidvi dvipng feynmf fragmaster lacheck latex-cjk-all \
    latexmk lcdf-typetools prerex psutils purifyeps t1utils tex-gyre latexdiff \
    texlive-base texlive-bibtex-extra texlive-binaries texlive-extra-utils \
    texlive-font-utils texlive-fonts-extra texlive-fonts-extra-links \
    texlive-fonts-recommended texlive-formats-extra texlive-games \
    texlive-humanities texlive-latex-base texlive-latex-extra \
    texlive-latex-recommended texlive-luatex texlive-metapost \
    texlive-music texlive-pictures texlive-plain-generic \
    texlive-pstricks texlive-publishers texlive-science \
    texlive-xetex tipa vprerex && apt-get autoclean

# Installing additional tools (mostly CLI)

RUN apt-get install -y zsh ripgrep git
